server:
  port: 20086
spring:
  application:
    name: aiyou-register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20086/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false     #关闭自我保护模式
    eviction-interval-timer-in-ms: 10000  #定期清理无效链接