server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://47.96.165.193:3306/aiyou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
   # url: jdbc:mysql:///aiyou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: YCH670989882@qq.com
   # password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.96.165.193
    password: YCH670989882@qq.com
  rabbitmq:
    host: 134.175.99.101
    virtual-host: /leyou
    username: leyou
    password: leyou
logging:
  level:
    cn:
      aiyou:
        user:
          mapper: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:20086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: cn.aiyou.user.pojo
