server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: F:\\idea\\aiyou\\rsa\\rsa.pub # 公钥地址
    priKeyPath: F:\\idea\\aiyou\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookiename: LY_TOKEN
ribbon:
  eureka:
    enabled: true

