server:
  port: 10010
spring:
  application:
    name: aiyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20086/eureka
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 60000

leyou:
  jwt:
    pubKeyPath: F:\\idea\\aiyou\\rsa\\rsa.pub # 公钥地址
    cookiename: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
